# Generated by Django 5.2 on 2025-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id_anggota', models.BigAutoField(primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('tgl_daftar', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=15)),
                ('password_hash', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Anggota',
            },
        ),
    ]
