# Generated by Django 4.2.25 on 2025-10-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='nip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
