# Generated by Django 4.2.25 on 2025-10-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0002_alter_anggota_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='alasan_nonaktif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anggota',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anggota',
            name='tanggal_nonaktif',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anggota',
            name='umur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
