# Generated by Django 5.2.1 on 2025-09-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpanan',
            name='dana_sosial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dana sosial yang disisihkan dari simpanan', max_digits=18),
        ),
    ]
