# Generated by Django 4.2.25 on 2025-12-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0002_simpanan_dana_sosial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTabungan',
            fields=[
                ('id_history', models.BigAutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('jenis_transaksi', models.CharField(choices=[('SETOR', 'Setor'), ('TARIK', 'Tarik'), ('KOREKSI', 'Koreksi')], max_length=10)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'history_tabungan',
                'managed': False,
            },
        ),
    ]
