# Generated by Django 4.2.25 on 2025-10-28 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0003_anggota_alasan_nonaktif_anggota_pekerjaan_and_more'),
        ('simpanan', '0002_simpanan_dana_sosial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTabungan',
            fields=[
                ('id_history', models.BigAutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('jenis_transaksi', models.CharField(choices=[('SETOR', 'Setoran'), ('TARIK', 'Penarikan')], max_length=10)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=18)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
                ('jenis_simpanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpanan.jenissimpanan')),
            ],
            options={
                'db_table': 'History_Tabungan',
                'ordering': ['-tanggal'],
            },
        ),
    ]
